const key='td91-quests-v1';
const initial=[{title:'Mijn portfolio vormgeven',step:'Kies één project en beschrijf wat ik ermee wil vertellen.',status:'Bezig',notes:'Voorstel om mee te starten — pas gerust aan.'},{title:'Een digitale ervaring bouwen',step:'Schets een kleine interactieve demo.',status:'Idee',notes:'Voorstel: web, pixel-art of een Digihulp-project.'},{title:'Meer ruimte voor creativiteit',step:'Plan één haalbaar creatief moment.',status:'Idee',notes:'Ik kies een haalbare volgende stap.'}];
let goals=structuredClone(initial);let available=true;
try{const s=localStorage.getItem(key);if(s){const parsed=JSON.parse(s);if(valid(parsed))goals=parsed}}catch{available=false}
function valid(a){return Array.isArray(a)&&a.length<=100&&a.every(g=>g&&['title','step','status','notes'].every(k=>typeof g[k]==='string'&&g[k].length<10000)&&['Idee','Bezig','Voltooid'].includes(g.status))}
const root=document.querySelector('#goals'),notice=document.querySelector('#notice');
function save(){try{localStorage.setItem(key,JSON.stringify(goals));notice.textContent='Bewaard in deze browser.'}catch{notice.textContent='Bewaren in deze browser lukt niet. Gebruik Exporteer doelen.'}summary()}
function summary(){document.querySelector('#summary').textContent=`${goals.filter(g=>g.status==='Voltooid').length} / ${goals.length} doelen voltooid`}
function render(){root.replaceChildren();goals.forEach((g,i)=>{const col=document.createElement('div');col.className='col-md-6 col-xl-4';const card=document.createElement('article');card.className='goal-card';const mark=document.createElement('span');mark.className='eyebrow';mark.textContent='DOEL '+String(i+1).padStart(2,'0');card.append(mark);for(const [field,label] of [['title','Mijn doel'],['step','Volgende kleine stap'],['status','Voortgang'],['notes','Notities & reflectie']]){const l=document.createElement('label');l.textContent=label;const el=document.createElement(field==='status'?'select':field==='notes'?'textarea':'input');if(field==='status')for(const s of ['Idee','Bezig','Voltooid']){const o=document.createElement('option');o.value=s;o.textContent=s;el.append(o)}else el.maxLength=9999;el.value=g[field];el.addEventListener('input',()=>{g[field]=el.value;save()});l.append(el);card.append(l)}const b=document.createElement('button');b.className='btn btn-outline-light btn-sm';b.textContent='Verwijder doel';b.addEventListener('click',()=>{if(confirm('Dit doel verwijderen?')){goals.splice(i,1);save();render()}});card.append(b);col.append(card);root.append(col)});summary()}
document.querySelector('#add-goal').onclick=()=>{if(goals.length>=100)return;goals.push({title:'Nieuw doel',step:'',status:'Idee',notes:''});save();render();root.lastElementChild.querySelector('input').focus()};
document.querySelector('#export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(goals,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='thomas-doelen.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
document.querySelector('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error();const data=JSON.parse(await file.text());if(!valid(data))throw Error();if(confirm('Huidige doelen vervangen door dit bestand?')){goals=data;save();render()}}catch{notice.textContent='Dit bestand bevat geen geldig doelen-overzicht.'}e.target.value=''};
const dialog=document.querySelector('#project-dialog');document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{document.querySelector('#dialog-title').textContent=['Saradomin’s Light','Mijn passie voor pixel-art','Motion Tales'][Number(b.dataset.project)];dialog.showModal()});document.querySelector('#close-dialog').onclick=()=>dialog.close();render();if(!available)notice.textContent='Gebruik Exporteer doelen als bewaren in deze browser niet lukt.';
